woong-jae/Algorithm-Crash

Programmers/[64061] 크레인 인형뽑기 게임/ONE/64061.java
Programmers/[64061] 크레인 인형뽑기 게임/ONE/README.md

ONE: [64061] 크레인 인형뽑기 게임

---

Programmers/[64065] 튜플/ONE/64065.java
Programmers/[64065] 튜플/ONE/README.md

ONE: [64065] 튜플

---

Programmers/[64061] 크레인 인형뽑기 게임/woong-jae/65061.js
Programmers/[64061] 크레인 인형뽑기 게임/woong-jae/README.md

woong-jae: [64061] 크레인 인형뽑기 게임

---

Programmers/[64065] 튜플/woong-jae/64065.js
Programmers/[64065] 튜플/woong-jae/README.md

woong-jae: [64065] 튜플

---

Programmers/[67256] 키패드 누르기/KingDonggyu/67256.js
Programmers/[67256] 키패드 누르기/KingDonggyu/README.md

KingDonggyu: [67256] 키패드 누르기

---

Programmers/[67257] 수식 최대화/KingDonggyu/67257.js
Programmers/[67257] 수식 최대화/KingDonggyu/README.md

KingDonggyu: [67257] 수식 최대화

---

Programmers/[67258] 보석 쇼핑/KingDonggyu/67258.js
Programmers/[67258] 보석 쇼핑/KingDonggyu/README.md

KingDonggyu: [67258] 보석 쇼핑

---

Programmers/[67259] 경주로 건설/KingDonggyu/67259.js
Programmers/[67259] 경주로 건설/KingDonggyu/README.md

KingDonggyu: [67259] 경주로 건설

---

Programmers/[67260] 동굴 탐험/KingDonggyu/67260.js
Programmers/[67260] 동굴 탐험/KingDonggyu/README.md

KingDonggyu: [67260] 동굴 탐험

---

Programmers/[67256] 키패드 누르기/ONE/67256.java
Programmers/[67256] 키패드 누르기/ONE/README.md

ONE: [67256] 키패드 누르기

---

Programmers/[67257] 수식 최대화/ONE/67257.java
Programmers/[67257] 수식 최대화/ONE/README.md

ONE: [67257] 수식 최대화

---

Programmers/[67258] 보석 쇼핑/ONE/67258.java
Programmers/[67258] 보석 쇼핑/ONE/README.md

ONE: [67258] 보석 쇼핑

---

Programmers/[67259] 경주로 건설/ONE/67259.java
Programmers/[67259] 경주로 건설/ONE/README.md

ONE: [67259] 경주로 건설

---

Programmers/[67260] 동굴 탐험/67260.java
Programmers/[67260] 동굴 탐험/README.md

ONE: [67260] 동굴 탐험

---

Programmers/[67257] 수식 최대화/SUbbb/67257.java
Programmers/[67257] 수식 최대화/SUbbb/README.md

SUbbb: [67257] 수식 최대화

---

Programmers/[67258] 보석 쇼핑/SUbbb/67258.java
Programmers/[67258] 보석 쇼핑/SUbbb/README.md

SUbbb: [67258] 보석 쇼핑

---

Programmers/[67259] 경주로 건설/SUbbb/67259.java
Programmers/[67259] 경주로 건설/SUbbb/README.md

SUbbb: [67259] 경주로 건설

---

Programmers/[67260] 동굴 탐험/SUbbb/67260.java
Programmers/[67260] 동굴 탐험/SUbbb/README.md

SUbbb: [67260] 동굴 탐험

---

Programmers/[67256] 키패드 누르기/woong-jae/67256.js
Programmers/[67256] 키패드 누르기/woong-jae/README.md

woong-jae: [67256] 키패드 누르기

---

Programmers/[67260] 동굴 탐험/woong-jae/67260.js
Programmers/[67260] 동굴 탐험/woong-jae/README.md
Programmers/[67260] 동굴 탐험/woong-jae/efficiency _fail.js

woong-jae: [67260] 동굴 탐험

---

Programmers/[67256] 키패드 누르기/JFe/67256.py
Programmers/[67256] 키패드 누르기/JFe/README.md

JFe: [67256] 키패드 누르기

---

Programmers/[67257] 수식 최대화/JFe/67257.py
Programmers/[67257] 수식 최대화/JFe/README.md

JFe: [67257] 수식 최대화

---

Programmers/[81301] 숫자 문자열과 영단어/SUbbb/81301.java
Programmers/[81301] 숫자 문자열과 영단어/SUbbb/README.md

시간 복잡도: O(NlogN)
문자열 배열 탐색
Map 탐색

SUbbb: [81301] 숫자 문자열과 영단어

---

Programmers/[81302] 거리두기 확인하기/SUbbb/81302.java
Programmers/[81302] 거리두기 확인하기/SUbbb/README.md

SUbbb: [81302] 거리두기 확인하기

---

Programmers/[81303] 표 편집/SUbbb/81303.java
Programmers/[81303] 표 편집/SUbbb/README.md

SUbbb: [81303] 표 편집

---

Programmers/[81304] 미로 탈출/SUbbb/81304.java
Programmers/[81304] 미로 탈출/SUbbb/README.md

SUbbb: [81304] 미로 탈출

---

Programmers/[81301] 숫자 문자열과 영단어/JFe/81301.py
Programmers/[81301] 숫자 문자열과 영단어/JFe/README.md

JFe: [81301] 숫자 문자열과 영단어

---

Programmers/[81303] 표 편집/JFe/81303.py
Programmers/[81303] 표 편집/JFe/README.md

JFe: [81303] 표 편집

---

Programmers/[81304] 미로 탈출/JFe/81304.py
Programmers/[81304] 미로 탈출/JFe/README.md

JFe: [81304] 미로 탈출

---

Programmers/[81303] 표 편집/woong-jae/81303.js
Programmers/[81303] 표 편집/woong-jae/README.md
Programmers/[81303] 표 편집/woong-jae/efficiency_fail.js

woong-jae: [81303] 표 편집

---

Programmers/[81304] 미로 탈출/woong-jae/81304.js
Programmers/[81304] 미로 탈출/woong-jae/README.md

woong-jae: [81304] 미로 탈출

---

Programmers/[81305] 시험장 나누기/woong-jae/81305.js
Programmers/[81305] 시험장 나누기/woong-jae/81305_efficiency_fail.js
Programmers/[81305] 시험장 나누기/woong-jae/README.md

woong-jae:  [81305] 시험장 나누기

---

Programmers/[81301] 숫자 문자열과 영단어 / ONE/81301.java
Programmers/[81301] 숫자 문자열과 영단어 / ONE/README.md

ONE: [81301] 숫자 문자열과 영단어

---

Programmers/[81302] 거리두기 확인하기/ONE/81302.java
Programmers/[81302] 거리두기 확인하기/ONE/README.md

ONE: [81302] 거리두기 확인하기

---

Programmers/[81303] 표 편집/ONE/81303.java
Programmers/[81303] 표 편집/ONE/README.md

ONE: [81303] 표 편집

---

Programmers/[83104] 미로 탈출/ONE/81304.java
Programmers/[83104] 미로 탈출/ONE/README.md

ONE: [81304] 미로 탈출

---

Programmers/[81301] 숫자 문자열과 영단어/KingDonggyu/81301.js
Programmers/[81301] 숫자 문자열과 영단어/KingDonggyu/README.md

KingDonggyu: [81301] 숫자 문자열과 영단어

---

Programmers/[81302] 거리두기 확인하기/KingDonggyu/81302.js
Programmers/[81302] 거리두기 확인하기/KingDonggyu/README.md

KingDonggyu: [81302] 거리두기 확인하기

---

Programmers/[81301] 숫자 문자열과 영단어/Johoseong/81301.py
Programmers/[81301] 숫자 문자열과 영단어/Johoseong/README.md

Johoseong: [81301] 숫자 문자열과 영단어

---

Programmers/[81303] 표 편집/Johoseong/81303.py
Programmers/[81303] 표 편집/Johoseong/README.md

Johoseong: [81303] 표 편집

---

Programmers/[81304] 미로 탈출/Johoseong/81304.py
Programmers/[81304] 미로 탈출/Johoseong/README.md

Johoseong: [81304] 미로 탈출

---

Programmers/[64064] 불량 사용자/KingDonggyu/64064.js
Programmers/[64064] 불량 사용자/KingDonggyu/README.md

KingDonggyu: [64064] 불량 사용자

---

BOJ/[16472] 고냥이/Johoseong/16472.py
BOJ/[16472] 고냥이/Johoseong/README.md

Johoseong: [16472] 고냥이

---

Programmers/[64064] 불량 사용자/Johoseong/64064.py
Programmers/[64064] 불량 사용자/Johoseong/README.md

Johoseong: [64064] 불량 사용자

---

Programmers/[64064] 불량 사용자/SUbbb/64064.java
Programmers/[64064] 불량 사용자/SUbbb/README.md

SUbbb: [64064] 불량 사용자

---

Programmers/[64062] 징검다리 건너기/SUbbb/64062.java
Programmers/[64062] 징검다리 건너기/SUbbb/README.md

SUbbb: [64062] 징검다리 건너기

---

BOJ/[16472] 고냥이/SUbbb/16472.java
BOJ/[16472] 고냥이/SUbbb/README.md

SUbbb: [16472] 고냥이

---

Programmers/[64063] 호텔 방 배정/SUbbb/64063.java
Programmers/[64063] 호텔 방 배정/SUbbb/README.md

SUbbb: [64063] 호텔 방 배정

---

Programmers/[64064] 불량 사용자/ONE/64064.java
Programmers/[64064] 불량 사용자/ONE/README.md

ONE: [64064] 불량 사용자

---

BOJ/[1083] 소트/ONE/1083.java
BOJ/[1083] 소트/ONE/README.md

ONE: [1083] 소트

---

BOJ/[16472] 고냥이/ONE/16472.java
BOJ/[16472] 고냥이/ONE/README.md

ONE: [16472] 고냥이

---

Programmers/[64062] 징검다리 건너기/ONE/64062.java
Programmers/[64062] 징검다리 건너기/ONE/README.md

ONE: [64062] 징검다리 건너기

---

Programmers/[64063] 호텔 방 배정/ONE/64063.java
Programmers/[64063] 호텔 방 배정/ONE/README.md

ONE: [64063] 호텔 방 배정

---

Programmers/[64064] 불량 사용자/JFe/64064.py
Programmers/[64064] 불량 사용자/JFe/README.md

JFe: [64064] 불량 사용자

---

BOJ/[1083] 소트/woong-jae/1083.js
BOJ/[1083] 소트/woong-jae/README.md

woong-jae: [1083] 소트

---

BOJ/[16472] 고냥이/woong-jae/16472.js
BOJ/[16472] 고냥이/woong-jae/README.md

woong-jae: [16472] 고냥이

---

Programmers/[64062] 징검다리 건너기/woong-jae/64062.js
Programmers/[64062] 징검다리 건너기/woong-jae/README.md

woong-jae: [64062] 징검다리 건너기

---

Programmers/[64063] 호텔 방 배정/woong-jae/64063.js
Programmers/[64063] 호텔 방 배정/woong-jae/README.md

woong-jae: [64063] 호텔 방 배정

---

Programmers/[64064] 불량 사용자/woong-jae/64064.js
Programmers/[64064] 불량 사용자/woong-jae/README.md

woong-jae: [64064] 불량 사용자

---

Programmers/[17676] 추석 트래픽/KingDonggyu/17676.js
Programmers/[17676] 추석 트래픽/KingDonggyu/README.md

KingDonggyu: [17676] 추석 트래픽

---

Programmers/[17677] 뉴스 클러스터링/KingDonggyu/17677.js
Programmers/[17677] 뉴스 클러스터링/KingDonggyu/README.md

KingDonggyu: [17677] 뉴스 클러스터링

---

Programmers/[17677] 뉴스 클러스터링/SUbbb/17677.java
Programmers/[17677] 뉴스 클러스터링/SUbbb/README.md

SUbbb: [17677] 뉴스 클러스터링

---

Programmers/[17680] 캐시/SUbbb/17680.java
Programmers/[17680] 캐시/SUbbb/README.md

SUbbb: [17680] 캐시

---

Programmers/[17676] 추석 트래픽/SUbbb/17676.java
Programmers/[17676] 추석 트래픽/SUbbb/README.md

SUbbb: [17676] 추석 트래픽

---

Programmers/[17678] 셔틀버스/SUbbb/17678.java
Programmers/[17678] 셔틀버스/SUbbb/README.md

SUbbb: [17678] 셔틀버스

---

Programmers/[17679] 프렌즈4블록/SUbbb/17679.java
Programmers/[17679] 프렌즈4블록/SUbbb/README.md

SUbbb: [17679] 프렌즈4블록

---

Programmers/[17676] 추석 트래픽/ONE/17676.java
Programmers/[17676] 추석 트래픽/ONE/README.md

ONE: [17676] 추석 트래픽

---

Programmers/[17677] 뉴스 클러스터링/ONE/17677.java
Programmers/[17677] 뉴스 클러스터링/ONE/README.md

ONE: [17677] 뉴스 클러스터링

---

Programmers/[17676] 추석 트래픽/woong-jae/17676.js
Programmers/[17676] 추석 트래픽/woong-jae/README.md

woong-jae: [17676] 추석 트래픽

---

Programmers/[17678] 셔틀버스/ONE/17678.java
Programmers/[17678] 셔틀버스/ONE/README.md

ONE: [17678] 셔틀버스

---

Programmers/[17679] 프렌즈4블록/ONE/17679.java
Programmers/[17679] 프렌즈4블록/ONE/README.md

ONE: [17679] 프렌즈4블록

---

Programmers/[17679] 프렌즈4블록/woong-jae/17679.js
Programmers/[17679] 프렌즈4블록/woong-jae/README.md

woong-jae: [17679] 프렌즈4블록

---

Programmers/[17680] 캐시/ONE/17680.java
Programmers/[17680] 캐시/ONE/README.md

ONE: [17680] 캐시

---

Programmers/[17678] 셔틀버스/woong-jae/17678.js
Programmers/[17678] 셔틀버스/woong-jae/README.md

woong-jae: [17678] 셔틀버스

---

Programmers/[17677] 뉴스 클러스터링/woong-jae/17677.js
Programmers/[17677] 뉴스 클러스터링/woong-jae/README.md

woong-jae: [17677] 뉴스 클러스터링

---

Programmers/[17677] 뉴스 클러스터링/JFe/17677.py
Programmers/[17677] 뉴스 클러스터링/JFe/README.md

JFe: [17677] 뉴스 클러스터링

---

Programmers/[17678] 셔틀버스/JFe/17678.py
Programmers/[17678] 셔틀버스/JFe/README.md

JFe: [17678] 셔틀버스

---

Programmers/[17680] 캐시/Johoseong/17680.py
Programmers/[17680] 캐시/Johoseong/README.md

Johoseong: [17680] 캐시

---

Programmers/[17678] 셔틀버스/Johoseong/17678.py
Programmers/[17678] 셔틀버스/Johoseong/README.md

Johoseong: [17678] 셔틀버스

---

Programmers/[17686] 파일명 정렬/ONE/17686.java
Programmers/[17686] 파일명 정렬/ONE/README.md

ONE: [17686] 파일명 정렬

---

Programmers/[17685] 자동완성/ONE/17685.java
Programmers/[17685] 자동완성/ONE/README.md

ONE: [17685] 자동완성

---

Programmers/[17687] n진수 게임/ONE/17687.java
Programmers/[17687] n진수 게임/ONE/README.md

ONE: [17687] n진수 게임

---

Programmers/[42891] 무지의 먹방 라이브/ONE/42891.java
Programmers/[42891] 무지의 먹방 라이브/ONE/README.md

ONE: [42891] 무지의 먹방 라이브

---

Programmers/[42893] 매칭  점수/ONE/42893.java
Programmers/[42893] 매칭  점수/ONE/README.md

ONE: [42893] 매칭 점수

---

Programmers/[17683] 방금그곡/SUbbb/17683.java
Programmers/[17683] 방금그곡/SUbbb/README.md

SUbbb: [17683] 방금그곡

---

Programmers/[17685] 자동완성/SUbbb/17685.java
Programmers/[17685] 자동완성/SUbbb/README.md

SUbbb: [17685] 자동완성

---

Programmers/[17687] n진수 게임/SUbbb/17687.java
Programmers/[17687] n진수 게임/SUbbb/README.md

SUbbb: [17687] n진수 게임

---

Programmers/[42890] 후보키/SUbbb/42890.java
Programmers/[42890] 후보키/SUbbb/README.md

SUbbb: [42890] 후보키

---

Programmers/[42893] 매칭 점수/SUbbb/42893.java
Programmers/[42893] 매칭 점수/SUbbb/README.md

SUbbb: [42893] 매칭 점수

---

Programmers/[42894] 블록 게임/SUbbb/42894.java
Programmers/[42894] 블록 게임/SUbbb/README.md

SUbbb: [42894] 블록 게임

---

Programmers/[42894] 블록 게임/woong-jae/42894.js
Programmers/[42894] 블록 게임/woong-jae/README.md

woong-jae: [42894] 블록 게임

---

Programmers/[42893] 매칭 점수/woong-jae/42893.js
Programmers/[42893] 매칭 점수/woong-jae/README.md

woong-jae: [42893] 매칭 점수

---

Programmers/[42892] 길 찾기 게임/woong-jae/42892.js
Programmers/[42892] 길 찾기 게임/woong-jae/README.md

woong-jae: [42892] 길 찾기 게임

---

Programmers/[42890] 후보키/woong-jae/42890.js
Programmers/[42890] 후보키/woong-jae/README.md

woong-jae: [42890] 후보키

---

Programmers/[17687] n진수 게임/woong-jae/17687.js
Programmers/[17687] n진수 게임/woong-jae/README.md

woong-jae: [17687] n진수 게임

---

Programmers/ [17686] 파일명 정렬/woong-jae/17686.js
Programmers/ [17686] 파일명 정렬/woong-jae/README.md

시간복잡도: $O(NM \log N)$ (M은 단어의 길이)

woong-jae: [17686] 파일명 정렬

---

Programmers/[17685] 자동완성/woong-jae/17685.js
Programmers/[17685] 자동완성/woong-jae/README.md

woong-jae: [17685] 자동완성

---

Programmers/[17684] 압축/woong-jae/17684.js
Programmers/[17684] 압축/woong-jae/README.md

woong-jae: [17684] 압축

---

Programmers/[17683] 방금그곡/woong-jae/17683.js
Programmers/[17683] 방금그곡/woong-jae/README.md

woong-jae: [17683] 방금그곡

---

Programmers/[17683] 방금그곡/KingDonggyu/17683.js
Programmers/[17683] 방금그곡/KingDonggyu/README.md

KingDonggyu: [17683] 방금그곡

---

Programmers/[42890] 후보키/KingDonggyu/42890.js
Programmers/[42890] 후보키/KingDonggyu/README.md

KingDonggyu: [42890] 후보키

---

Programmers/[42891] 무지의 먹방 라이브/KingDonggyu/42891.js
Programmers/[42891] 무지의 먹방 라이브/KingDonggyu/README.md

KingDonggyu: [42891] 무지의 먹방 라이브

---

Programmers/[42892] 길 찾기 게임/KingDonggyu/42892.js
Programmers/[42892] 길 찾기 게임/KingDonggyu/README.md

KingDonggyu: [42892] 길 찾기 게임

---

Programmers/[42893] 매칭 점수/KingDonggyu/42893.js
Programmers/[42893] 매칭 점수/KingDonggyu/README.md

KingDonggyu: [42893] 매칭 점수

---

Programmers/[17684] 압축/JFe/17684.py
Programmers/[17684] 압축/JFe/README.md

JFe: [17684] 압축

---

Programmers/[17685] 자동완성/JFe/17685.py
Programmers/[17685] 자동완성/JFe/README.md

JFe: [17685] 자동완성

---

Programmers/[17686] 파일명 정렬/JFe/17686.py
Programmers/[17686] 파일명 정렬/JFe/README.md

JFe: [17686] 파일명 정렬

---

Programmers/[42890] 후보키/JFe/42890.py
Programmers/[42890] 후보키/JFe/README.md

JFe: [42890] 후보키

---

Programmers/[42892] 길 찾기 게임/JFe/42892.py
Programmers/[42892] 길 찾기 게임/JFe/README.md

JFe: [42892] 길 찾기 게임

---

Programmers/[42893] 매칭 점수/JFe/42893.py
Programmers/[42893] 매칭 점수/JFe/README.md

JFe: [42893] 매칭 점수

---

Programmers/[42894] 블록게임/Johoseong/42894.py
Programmers/[42894] 블록게임/Johoseong/README.md

Johoseong: [42894] 블록게임

---

Programmers/[17683] 방금그곡/Johoseong/17683.py
Programmers/[17683] 방금그곡/Johoseong/README.md

Johoseong: [17683] 방금그곡

---

Programmers/[17684] 압축/Johoseong/17684.py
Programmers/[17684] 압축/Johoseong/README.md

Johoseong: [17684] 압축

---

Programmers/[17685] 자동완성/Johoseong/17685.py
Programmers/[17685] 자동완성/Johoseong/README.md

Johoseong: [17685] 자동완성

---

Programmers/[17686] 파일명 정렬/Johoseong/17686.py
Programmers/[17686] 파일명 정렬/Johoseong/README.md

Johoseong: [17686] 파일명 정렬

---

Programmers/[17687] n진수 게임/Johoseong/17687.py
Programmers/[17687] n진수 게임/Johoseong/README.md

Johoseong: [17687] n진수 변환

---

Programmers/[42891] 무지의 먹방 라이브/Johoseong/42891.py
Programmers/[42891] 무지의 먹방 라이브/Johoseong/README.md

Johoseong: [42891] 무지의 먹방 라이브

---

Programmers/[42890] 후보키/Johoseong/42890.py
Programmers/[42890] 후보키/Johoseong/README.md

Johoseong: [42890] 후보키

---

Programmers/[42892] 길 찾기 게임/Johoseong/42892.py
Programmers/[42892] 길 찾기 게임/Johoseong/README.md

Johoseong: [42892] 길 찾기 게임

---

Programmers/[42893] 매칭 점수/Johoseong/42893.py
Programmers/[42893] 매칭 점수/Johoseong/README.md

Johoseong: [42893] 매칭 점수

---

Programmers/[42889] 실패율/woong-jae/42889.js
Programmers/[42889] 실패율/woong-jae/README.md

woong-jae: [42889] 실패율

---

Programmers/[42888] 오픈채팅방/woong-jae/42888.js
Programmers/[42888] 오픈채팅방/woong-jae/README.md

woong-jae: [42888] 오픈채팅방

---

Programmers/[60057] 문자열 압축/woong-jae/60057.js
Programmers/[60057] 문자열 압축/woong-jae/README.md

woong-jae: [60057] 문자열 압축

---

Programmers/[60058] 괄호 변환/woong-jae/60058.js
Programmers/[60058] 괄호 변환/woong-jae/README.md

woong-jae: [60057] 괄호 변환

---

Programmers/[60059] 자물쇠와 열쇠/woong-jae/60059.js
Programmers/[60059] 자물쇠와 열쇠/woong-jae/README.md

woong-jae: [60059] 자물쇠와 열쇠

---

Programmers/[42889] 실패율/KingDonggyu/42889.js
Programmers/[42889] 실패율/KingDonggyu/README.md

KingDonggyu: [42889] 실패율

---

Programmers/[60058] 괄호 변환/KingDonggyu/60058.js
Programmers/[60058] 괄호 변환/KingDonggyu/README.md

KingDonggyu: [60058] 괄호 변환

---

Programmers/[42889] 실패율/SUbbb/42889.java
Programmers/[42889] 실패율/SUbbb/README.md

SUbbb: [42889] 실패율

---

Programmers/[42888] 오픈채팅방/SUbbb/42888.java
Programmers/[42888] 오픈채팅방/SUbbb/README.md

SUbbb: [42888] 오픈채팅방

---

Programmers/[60057] 문자열 압축/SUbbb/60057.java
Programmers/[60057] 문자열 압축/SUbbb/README.md

SUbbb: [60057] 문자열 압축

---

Programmers/[60058] 괄호 변환/SUbbb/60058.java
Programmers/[60058] 괄호 변환/SUbbb/README.md

SUbbb: [60058] 괄호 변환

---

Programmers/[42889] 실패율/ONE/42889.java
Programmers/[42889] 실패율/ONE/README.md

ONE: [42889] 실패울

---

Programmers/[60057] 문자열 압축/ONE/60057.java
Programmers/[60057] 문자열 압축/ONE/README.md

ONE: [60057] 문자열 압축

---

Programmers/[60058] 괄호 변환/ONE/60058.java
Programmers/[60058] 괄호 변환/ONE/README.md

ONE: [60058] 괄호 변환

---

Programmers/[42889] 실패율/JFe/42889.py
Programmers/[42889] 실패율/JFe/README.md

JFe: [42889] 실패율

---

Programmers/[42888] 오픈채팅방/JFe/42888.py
Programmers/[42888] 오픈채팅방/JFe/README.md

JFe: [42888] 오픈채팅방

---

Programmers/[60057] 문자열 압축/JFe/60057.py
Programmers/[60057] 문자열 압축/JFe/README.md

JFe: [60057] 문자열 압축

---

Programmers/[60058] 괄호 변환/JFe/60058.py
Programmers/[60058] 괄호 변환/JFe/README.md

JFe: [60058] 괄호 변환

---

Programmers/[60059] 자물쇠와 열쇠/JFe/60059.py
Programmers/[60059] 자물쇠와 열쇠/JFe/README.md

JFe: [60059] 자물쇠와 열쇠

---

Programmers/[60058] 괄호 변환/Johoseong/60058.py
Programmers/[60058] 괄호 변환/Johoseong/README.md

Johoseong: [60058] 괄호 변환

---

Programmers/[42888] 오픈채팅방/Johoseong/42888.py
Programmers/[42888] 오픈채팅방/Johoseong/README.md

Johoseong: [42888] 오픈채팅방

---

Programmers/[42889] 실패율/Johoseong/42889.py
Programmers/[42889] 실패율/Johoseong/README.md

Johoseong: [42889] 실패율

---

Programmers/[60057] 문자열 압축/Johoseong/60057.py
Programmers/[60057] 문자열 압축/Johoseong/REAMD.md

Johoseong: [60057] 문자열 압축

---

Programmers/[60060] 가사 검색/KingDonggyu/60060.js
Programmers/[60060] 가사 검색/KingDonggyu/README.md

KingDonggyu: [60060] 가사 검색

---

Programmers/[12914] 멀리 뛰기/ONE/12914.java
Programmers/[12914] 멀리 뛰기/ONE/README.md

ONE: [12914] 멀리 뛰기

---

Programmers/[60062] 외벽 점검/KingDonggyu/60062.js
Programmers/[60062] 외벽 점검/KingDonggyu/README.md

KingDonggyu: [60062] 외벽 점검

---

Programmers/[60063] 블록 이동하기/KingDonggyu/60063.js
Programmers/[60063] 블록 이동하기/KingDonggyu/README.md

KingDonggyu: [60063] 블록 이동하기

---

Programmers/[60062] 외벽 점검/ONE/60062.java
Programmers/[60062] 외벽 점검/ONE/README.md

ONE: [60062] 외벽 점검

---

Programmers/[60062] 외벽 점검/Johoseong/60062.py
Programmers/[60062] 외벽 점검/Johoseong/README.md

Johoseong: [60062] 외벽 점검

---

Programmers/[60063] 블록 이동하기/Johoseong/60063.py
Programmers/[60063] 블록 이동하기/Johoseong/README.md

Johoseong: [60063] 블록 이동하기

---

Programmers/[60061] 기둥과 보 설치/Johoseong/60061.py
Programmers/[60061] 기둥과 보 설치/Johoseong/README.md

Johoseong: [60061] 기둥과 보 설치

---

Programmers/[12914] 멀리 뛰기/Johoseong/12914.py
Programmers/[12914] 멀리 뛰기/Johoseong/README.md

Johoseong: [12914] 멀리 뛰기

---

Programmers/[60060] 가사 검색/Johoseong/60060.py
Programmers/[60060] 가사 검색/Johoseong/README.md

- 시간 복잡도: O(M*L) (M: 단어개수, L: 단어길이)

Johoseong: [60060] 가사 검색

---

Programmers/[60062] 외벽 점검/SUbbb/60062.java
Programmers/[60062] 외벽 점검/SUbbb/README.md

SUbbb: [60062] 외벽 점검

---

Programmers/[60063] 블록 이동하기/woong-jae/60063.js
Programmers/[60063] 블록 이동하기/woong-jae/README.md

시간복잡도: $O(N^2)$, $N$은 `board`의 길이

woong-jae: [60063] 블록 이동하기

---

Programmers/[60062] 외벽 점검/woong-jae/60062.js
Programmers/[60062] 외벽 점검/woong-jae/README.md

woong-jae: [60062] 외벽 점검

---

Programmers/[12914] 멀리 뛰기/woong-jae/12914.js
Programmers/[12914] 멀리 뛰기/woong-jae/README.md

woong-jae: [12914] 멀리 뛰기

---

Programmers/[60063] 블록 이동하기/JFe/60063.py
Programmers/[60063] 블록 이동하기/JFe/README.md

JFe: [60063] 블록 이동하기

---

Programmers/[72410] 신규 아이디 추천/SUbbb/72410.java
Programmers/[72410] 신규 아이디 추천/SUbbb/README.md

SUbbb: [72410] 신규 아이디 추천

---

Programmers/[72411] 메뉴 리뉴얼/SUbbb/72411.java
Programmers/[72411] 메뉴 리뉴얼/SUbbb/README.md

SUbbb: [72411] 메뉴 리뉴얼

---

Programmers/[72412] 순위 검색/SUbbb/72412.java
Programmers/[72412] 순위 검색/SUbbb/README.md

SUbbb: [72412] 순위 검색

---

Programmers/[72413] 합승 택시 요금/SUbbb/72413.java
Programmers/[72413] 합승 택시 요금/SUbbb/README.md

SUbbb: [72413] 합승 택시 요금

---

Programmers/[72412] 순위 검색/woong-jae/72412.js
Programmers/[72412] 순위 검색/woong-jae/README.md

woong-jae: [72412] 순위 검색

---

Programmers/[72413] 합승 택시 요금/woong-jae/72413.js
Programmers/[72413] 합승 택시 요금/woong-jae/README.md

woong-jae: [72413] 합승 택시 요금

---

Programmers/[72414] 광고 삽입/woong-jae/72414.js
Programmers/[72414] 광고 삽입/woong-jae/README.md

woong-jae: [72414] 광고 삽입

---

Programmers/[72411] 메뉴 리뉴얼/ONE/72411.java
Programmers/[72411] 메뉴 리뉴얼/ONE/README.md

ONE: [72411] 메뉴 리뉴얼

---

Programmers/[72412] 순위 검색/ONE/72412.java
Programmers/[72412] 순위 검색/ONE/README.md

ONE: [72412] 순위 검색

---

Programmers/[72413] 합승 택시 요금/ONE/72413.java
Programmers/[72413] 합승 택시 요금/ONE/README.md

ONE: [72413] 합승 택시 요금

---

Programmers/[72411] 메뉴 리뉴얼/KingDonggyu/72411.js
Programmers/[72411] 메뉴 리뉴얼/KingDonggyu/README.md

KingDonggyu: [72411] 메뉴 리뉴얼

---

Programmers/[72411] 메뉴 리뉴얼/JFe/72411.py
Programmers/[72411] 메뉴 리뉴얼/JFe/README.md

JFe: [72411] 메뉴 리뉴얼

---

Programmers/[72414] 광고 삽입/JFe/72414.py
Programmers/[72414] 광고 삽입/JFe/README.md

JFe: [72414] 광고 삽입

---

Programmers/[72411] 메뉴 리뉴얼/Johoseong/72411.py
Programmers/[72411] 메뉴 리뉴얼/Johoseong/README.md

Johoseong: [72411] 메뉴 리뉴얼

---

Programmers/[72412] 순위 검색/Johoseong/72412.py
Programmers/[72412] 순위 검색/Johoseong/README.md

Johoseong: [72412] 순위 검색

---

Programmers/[72413] 합승 택시 요금/Johoseong/72413.py
Programmers/[72413] 합승 택시 요금/Johoseong/README.md

Johoseong: [72413] 합승 택시 요금

---

Programmers/[72414] 광고 삽입/Johoseong/72414.py
Programmers/[72414] 광고 삽입/Johoseong/README.md

Johoseong: [72414] 광고 삽입

---

Programmers/[92335] k진수에서 소수 개수 구하기/woong-jae/92335.js
Programmers/[92335] k진수에서 소수 개수 구하기/woong-jae/README.md

woong-jae: [92335] k진수에서 소수 개수 구하기

---

Programmers/[92334] 신고 결과 받기/woong-jae/92334.js
Programmers/[92334] 신고 결과 받기/woong-jae/README.md

woong-jae: [92334] 신고 결과 받기

---

Programmers/[72416] 매출 하락 최소화/woong-jae/72416.js
Programmers/[72416] 매출 하락 최소화/woong-jae/README.md

woong-jae: [72416] 매출 하락 최소화

---

Programmers/[72415] 카드 짝 맞추기/woong-jae/72415.js
Programmers/[72415] 카드 짝 맞추기/woong-jae/README.md

woong-jae: [72415] 카드 짝 맞추기

---

Programmers/[72416] 매출 하락 최소화/Johoseong/72416.py
Programmers/[72416] 매출 하락 최소화/Johoseong/README.md

Johoseong: [72416] 매출 하락 최소화

---

Programmers/[92341] 주차 요금 계산/Johoseong/92341.py
Programmers/[92341] 주차 요금 계산/Johoseong/README.md

Johoseong: [92341] 주차 요금 계산

---

Programmers/[72415] 카드 짝 맞추기/Johoseong/72415.py
Programmers/[72415] 카드 짝 맞추기/Johoseong/README.md

Johoseong: [72415] 카드 짝 맞추기

---

Programmers/[92341] 주차 요금 계산/SUbbb/92341.java
Programmers/[92341] 주차 요금 계산/SUbbb/README.md

SUbbb: [92341] 주차 요금 계산

---

Programmers/[72415] 카드 짝 맞추기/SUbbb/72415.java
Programmers/[72415] 카드 짝 맞추기/SUbbb/README.md

SUbbb: [72415] 카드 짝 맞추기

---

Programmers/[72416] 매출 하락 최소화/SUbbb/72416.java
Programmers/[72416] 매출 하락 최소화/SUbbb/README.md

SUbbb: [72416] 매출 하락 최소화

---

Programmers/[72415] 카드 짝 맞추기/ONE/72415.java
Programmers/[72415] 카드 짝 맞추기/ONE/README.md

ONE: [72415] 카드 짝 맞추기

---

Programmers/[72416] 매출 하락 최소화/ONE/72416.java
Programmers/[72416] 매출 하락 최소화/ONE/README.md

ONE: [72416] 매출 하락 최소화

---

Programmers/[92334] 신고 결과 받기/ONE/92334.java
Programmers/[92334] 신고 결과 받기/ONE/README.md

ONE: [92334] 신고 결과 받기

---

Programmers/[92335] k진수에서 소수 개수 구하기/ONE/92335.java
Programmers/[92335] k진수에서 소수 개수 구하기/ONE/README.md

ONE: [92335] k진수에서 소수 개수 구하기 

---

Programmers/[92341] 주차 요금 계산/ONE/92341.java
Programmers/[92341] 주차 요금 계산/ONE/README.md

ONE: [92341] 주차 요금 계산

---

Programmers/[72415] 카드 짝 맞추기/JFe/72415.py

JFe: [72415] 카드 짝 맞추기

---

Programmers/[92334] 신고 결과 받기/JFe/92334.py
Programmers/[92334] 신고 결과 받기/JFe/README.md

JFe: [92334] 신고 결과 받기

---

Programmers/[92335] k진수에서 소수 개수 구하기/JFe/92335.py

JFe: [92335] k진수에서 소수 개수 구하기

---

Programmers/[92341] 주차 요금 계산/JFe/92341.py

JFe: [92341] 주차 요금 계산

---

Programmers/[72415] 카드 짝 맞추기/KingDonggyu/72415.js
Programmers/[72415] 카드 짝 맞추기/KingDonggyu/README.md
Programmers/[72415] 카드 짝 맞추기/KingDonggyu/firstCode.js

KingDonggyu: [72415] 카드 짝 맞추기

---

Programmers/[92334] 신고 결과 받기/KingDonggyu/92334.js
Programmers/[92334] 신고 결과 받기/KingDonggyu/README.md

KingDonggyu: [92334] 신고 결과 받기

---

Programmers/[92341] 주차 요금 계산/KingDonggyu/92341.js
Programmers/[92341] 주차 요금 계산/KingDonggyu/README.md

KingDonggyu: [92341] 주차 요금 계산

---

Programmers/[77484] 로또의 최고 순위와 최저 순위/ONE/77484.java
Programmers/[77484] 로또의 최고 순위와 최저 순위/ONE/README.md

ONE: [77484] 로또의 최고 순위와 최저 순위

---

Programmers/[92342] 양궁대회/ONE/92342.java
Programmers/[92342] 양궁대회/ONE/README.md

ONE: [92342] 양궁대회

---

Programmers/[92343] 양과 늑대/ONE/92343.java
Programmers/[92343] 양과 늑대/ONE/README.md

ONE: [92343] 양과 늑대

---

Programmers/[92344] 파괴되지 않은 건물/ONE/92344.java
Programmers/[92344] 파괴되지 않은 건물/ONE/README.md

ONE: [92344] 파괴되지 않은 건물

---

Programmers/[92345] 사라지는 발판/ONE/92345.java
Programmers/[92345] 사라지는 발판/ONE/README.md

ONE: [92345] 사라지는 발판

---

Programmers/[92343] 양과 늑대/woong-jae/92343.js
Programmers/[92343] 양과 늑대/woong-jae/README.md

woong-jae: [92343] 양과 늑대

---

Programmers/[92342] 양궁대회/woong-jae/92342.js
Programmers/[92342] 양궁대회/woong-jae/README.md

woong-jae: [92342] 양궁대회

---

Programmers/[77484] 로또의 최고 순위와 최저 순위/woong-jae/77484.js
Programmers/[77484] 로또의 최고 순위와 최저 순위/woong-jae/README.md

woong-jae: [77484] 로또의 최고 순위와 최저 순위

---

Programmers/[77484] 로또의 최고 순위와 최저 순위/SUbbb/77484.java
Programmers/[77484] 로또의 최고 순위와 최저 순위/SUbbb/README.md

SUbbb: [77484] 로또의 최고 순위와 최저 순위

---

Programmers/[92342] 양궁대회/SUbbb/92342.java
Programmers/[92342] 양궁대회/SUbbb/README.md

SUbbb: [92342] 양궁대회

---

Programmers/[92343] 양과 늑대/SUbbb/92343.java
Programmers/[92343] 양과 늑대/SUbbb/README.md

SUbbb: [92343] 양과 늑대

---

Programmers/[92344] 파괴되지 않은 건물/SUbbb/92344.java
Programmers/[92344] 파괴되지 않은 건물/SUbbb/README.md

SUbbb: [92344] 파괴되지 않은 건물

---

Programmers/[92345] 사라지는 발판/SUbbb/92345.java
Programmers/[92345] 사라지는 발판/SUbbb/README.md

SUbbb: [92345] 사라지는 발판

---

Programmers/[92344] 파괴되지 않은 건물/Johoseong/92344.py
Programmers/[92344] 파괴되지 않은 건물/Johoseong/README.md

- 시간 복잡도: O(M + N^2)  (M: skill 길이, N^2: 배열 크기)

Johoseong: [92344] 파괴되지 않은 건물

---

Programmers/[92343] 양과 늑대/Johoseong/92343.py
Programmers/[92343] 양과 늑대/Johoseong/README.md

Johoseong: [92343] 양과 늑대

---

Programmers/[92345] 사라지는 발판/Johoseong/92345.py
Programmers/[92345] 사라지는 발판/Johoseong/README.md

Johoseong: [92345] 사라지는 발판

---

Programmers/[77484] 로또의 최고 순위와 최저 순위/Johoseong/77484.py
Programmers/[77484] 로또의 최고 순위와 최저 순위/Johoseong/README.md

Johoseong: [77484] 로또의 최고 순위와 최저 순위

---

Programmers/[92342] 양궁대회/Johoseong/92342.py
Programmers/[92342] 양궁대회/Johoseong/README.md

- 시간 복잡도: O(N*2^N)   (N = 10 고정)

Johoseong: [92342] 양궁대회

---

Programmers/[92342] 양궁대회/JFe/92342.py

JFe: [92342] 양궁대회

---

Programmers/[92344] 파괴되지 않은 건물/JFe/92344.py

JFe: [92344] 파괴되지 않은 건물

---

Programmers/[92345] 사라지는 발판/JFe/92345.py

JFe: [92345] 사라지는 발판

---

Programmers/[77484] 로또의 최고 순위와 최저 순위/JFe/77484.py

JFe: [77484] 로또의 최고 순위와 최저 순위

---

Programmers/[77486] 다단계 칫솔 판매/SUbbb/77486.java
Programmers/[77486] 다단계 칫솔 판매/SUbbb/README.md

SUbbb: [77486] 다단계 칫솔 판매

---

Programmers/[86053] 금과 은 운반하기/SUbbb/86053.java
Programmers/[86053] 금과 은 운반하기/SUbbb/README.md

SUbbb: [86053] 금과 은 운반하기

---

Programmers/[77486] 다단계 칫솔 판매/ONE/77486.java
Programmers/[77486] 다단계 칫솔 판매/ONE/README.md

ONE: [77486] 다단계 칫솔 판매

---

Programmers/[86053] 금과 은 운반하기/ONE/86053.java
Programmers/[86053] 금과 은 운반하기/ONE/README.md

ONE: [86053] 금과 은 운반하기

---

Programmers/[62050] 지형 이동/ONE/62050.java
Programmers/[62050] 지형 이동/ONE/README.md

ONE: [62050] 지형 이동

---

Programmers/[86053] 금과 은 운반하기/Johoseong/86053.py
Programmers/[86053] 금과 은 운반하기/Johoseong/README.md

Johoseong: [86053] 금과 은 운반하기

---

Programmers/[62050] 지형 이동/Johoseong/62050.py
Programmers/[62050] 지형 이동/Johoseong/README.md

Johoseong: [62050] 지형 이동

---

Programmers/[77486] 다단계 칫솔 판매/Johoseong/77486.py
Programmers/[77486] 다단계 칫솔 판매/Johoseong/README.md

Johoseong: [77486] 다단계 칫솔 판매

---

Programmers/[12973] 짝지어 제거하기/Johoseong/12973.py
Programmers/[12973] 짝지어 제거하기/Johoseong/README.md

Johoseong: [12973] 짝지어 제거하기

---

Programmers/[62050] 지형 이동/woong-jae/62050.js
Programmers/[62050] 지형 이동/woong-jae/README.md

woong-jae: [62050] 지형 이동

---

Programmers/[86053] 금과 은 운반하기/woong-jae/86053.js
Programmers/[86053] 금과 은 운반하기/woong-jae/README.md

woong-jae: [86053] 금과 은 운반하기

---

Programmers/[77486] 다단계 칫솔 판매/woong-jae/77486.js
Programmers/[77486] 다단계 칫솔 판매/woong-jae/README.md

woong-jae: [77486] 다단계 칫솔 판매

---

Programmers/[12973] 짝지어 제거하기/woong-jae/12973.js
Programmers/[12973] 짝지어 제거하기/woong-jae/README.md

woong-jae: [12973] 짝지어 제거하기

---

Programmers/[12973] 짝지어 제거하기/JFe/12973.py
Programmers/[12973] 짝지어 제거하기/JFe/README.md

JFe: [12973] 짝지어 제거하기

---

Programmers/[77486] 다단계 칫솔 판매/JFe/77486.py
Programmers/[77486] 다단계 칫솔 판매/JFe/README.md

JFe: [77486] 다단계 칫솔 판매

---

Programmers/[86053] 금과 은 운반하기/JFe/86053.py
Programmers/[86053] 금과 은 운반하기/JFe/README.md

JFe: [86053] 금과 은 운반하기

---

Programmers/[12973] 짝지어 제거하기/KingDonggyu/12973.js
Programmers/[12973] 짝지어 제거하기/KingDonggyu/README.md

KingDonggyu: [12973] 짝지어 제거하기

---

Programmers/[86053] 금과 은 운반하기/GoldAndSilver.js
Programmers/[86053] 금과 은 운반하기/README.md

O(nlogT)
T = 10e5 * 4 * 10e9 (max time of moving time)

pinkishincoloragain Programmers 86053

---

Programmers/[12973] 짝지어 제거하기/pinkishincoloragain/12973.js
Programmers/[12973] 짝지어 제거하기/pinkishincoloragain/README.md

pinkishincoloragain: [12973] 짝지어 제거하기

---

Programmers/[77486] 다단계 칫솔 판매/README.md
Programmers/[77486] 다단계 칫솔 판매/pinkishincoloragain/Dadangye3.js

pinkishincoloragain Programmers 77486

---

Programmers/[86052] 빛의 경로 사이클/woong-jae/86052.js
Programmers/[86052] 빛의 경로 사이클/woong-jae/README.md

woong-jae: [86052] 빛의 경로 사이클

---

Programmers/[76503] 모두 0으로 만들기/woong-jae/76503.js
Programmers/[76503] 모두 0으로 만들기/woong-jae/README.md

woong-jae: [76503] 모두 0으로 만들기

---

Programmers/[77886] 110 옮기기/woong-jae/77886.js
Programmers/[77886] 110 옮기기/woong-jae/README.md

woong-jae: [77886] 110 옮기기

---

Programmers/[49995] 쿠키 구입/woong-jae/49995.js
Programmers/[49995] 쿠키 구입/woong-jae/README.md

woong-jae: [49995] 쿠키 구입

---

Programmers/[77485] 행렬 테두리 회전하기/ONE/77485.java
Programmers/[77485] 행렬 테두리 회전하기/ONE/README.md

ONE: [77485] 행렬 테두리 회전하기

---

Programmers/[86052] 빛의 경로 사이클/ONE/86052.java
Programmers/[86052] 빛의 경로 사이클/ONE/README.md

ONE: [86052] 빛의 경로 사이클

---

Programmers/[76503] 모두 0으로 만들기/ONE/76503.java
Programmers/[76503] 모두 0으로 만들기/ONE/README.md

ONE: [76503] 모두 0으로 만들기

---

Programmers/[49995] 쿠키 구입/ONE/49995.java
Programmers/[49995] 쿠키 구입/ONE/README.md

ONE: [49995] 쿠키 구입

---

Programmers/[77886] 110 옮기기/ONE/77886.java
Programmers/[77886] 110 옮기기/ONE/README.md

ONE: [77886] 110 옮기기

---

Programmers/[49995] 쿠키 구입/Johoseong/49995.py
Programmers/[49995] 쿠키 구입/Johoseong/README.md

Johoseong: [49995] 쿠키 구입

---

Programmers/[77485] 행렬 테두리 회전하기/pinkishincoloragain/README.md
Programmers/[77485] 행렬 테두리 회전하기/pinkishincoloragain/Rotate-1.js

pinkishincoloragain: [77485] 행렬 테두리 회전하기

---

Programmers/[76503] 모두 0으로 만들기/pinkishincoloragain/All0.js
Programmers/[76503] 모두 0으로 만들기/pinkishincoloragain/README.md

pinkishincoloragain: [76053] 모두 0으로 만들기

---

Programmers/[49995] 쿠키 구입/pinkishincoloragain/MoveCookie-1.js
Programmers/[49995] 쿠키 구입/pinkishincoloragain/README.md

pinkishincoloragain: [49995] 쿠키 구입

---

Programmers/[77886] 110 옮기기/pinkishincoloragain/Make110-4.js
Programmers/[77886] 110 옮기기/pinkishincoloragain/README.md

pinkishincoloragain: [77886] 110 옮기기

---

Programmers/[77485] 행렬 테두리 회전하기/Johoseong/77485.py
Programmers/[77485] 행렬 테두리 회전하기/Johoseong/README.md

Johoseong: [77485] 행렬 테두리 회전하기

---

Programmers/[86052] 빛의 경로 사이클/Johoseong/86052.py
Programmers/[86052] 빛의 경로 사이클/Johoseong/README.md

Johoseong: [86052] 빛의 경로 사이클

---

Programmers/[76503] 모두 0으로 만들기/Johoseong/76503.py
Programmers/[76503] 모두 0으로 만들기/Johoseong/README.md

Johoseong: [76503] 모두 0으로 만들기

---

Programmers/[86052] 빛의 경로 사이클/SUbbb/86052.java
Programmers/[86052] 빛의 경로 사이클/SUbbb/README.md

SUbbb: [86052] 빛의 경로 사이클

---

Programmers/[76503] 모두 0으로 만들기/SUbbb/76503.java
Programmers/[76503] 모두 0으로 만들기/SUbbb/README.md

SUbbb: [76503] 모두 0으로 만들기

---

Programmers/[77886] 110 옮기기/SUbbb/77886.java
Programmers/[77886] 110 옮기기/SUbbb/README.md

SUbbb: [77886] 110 옮기기

---

Programmers/[49995] 쿠키 구입/SUbbb/49995.java
Programmers/[49995] 쿠키 구입/SUbbb/README.md

SUbbb: [49995] 쿠키 구입

---

Programmers/[77485] 행렬 테두리 회전하기/JFe/77485.py
Programmers/[77485] 행렬 테두리 회전하기/JFe/README.md

JFe: [77485] 행렬 테두리 회전하기

---

Programmers/[86052] 빛의 경로 사이클/JFe/86052.py
Programmers/[86052] 빛의 경로 사이클/JFe/README.md

JFe: [86052] 빛의 경로 사이클

---

Programmers/[86054] 안티세포/Johoseong/86054.py
Programmers/[86054] 안티세포/Johoseong/README.md

Johoseong: [86054] 안티세포

---

Programmers/[87391] 공 이동 시뮬레이션/Johoseong/87391.py
Programmers/[87391] 공 이동 시뮬레이션/Johoseong/README.md

Johoseong: [87391] 공 이동 시뮬레이션

---

Programmers/[12985] 예상 대진표/Johoseong/12985.py
Programmers/[12985] 예상 대진표/Johoseong/README.md

Johoseong: [12985] 예상 대진표

---

Programmers/[76502] 괄호 회전하기/SUbbb/76502.java
Programmers/[76502] 괄호 회전하기/SUbbb/README.md

SUbbb: [76502] 괄호 회전하기

---

Programmers/[76502] 괄호 회전하기/Johoseong/76502.py
Programmers/[76502] 괄호 회전하기/Johoseong/README.md

Johoseong: [76502] 괄호 회전하기

---

Programmers/[87694] 아이템 줍기/SUbbb/87694.java
Programmers/[87694] 아이템 줍기/SUbbb/README.md

SUbbb: [87694] 아이템 줍기

---

Programmers/[87694] 아이템 줍기/Johoseong/87694.py
Programmers/[87694] 아이템 줍기/Johoseong/README.md

Johoseong: [87694] 아이템 줍기

---

Programmers/[76502] 괄호 회전하기/JFe/76502.py
Programmers/[76502] 괄호 회전하기/JFe/README.md

JFe: [76502] 괄호 회전하기

---

Programmers/[87694] 아이템 줍기/JFe/87694.py
Programmers/[87694] 아이템 줍기/JFe/README.md

JFe: [87694] 아이템 줍기

---

Programmers/[87391] 공 이동 시뮬레이션/JFe/87391.py
Programmers/[87391] 공 이동 시뮬레이션/JFe/README.md

JFe: [87391] 공 이동 시뮬레이션

---

Programmers/[12985] 예상 대진표/ONE/12985.java
Programmers/[12985] 예상 대진표/ONE/README.md

ONE: [12985] 예상 대진표

---

Programmers/[76502] 괄호 회전하기/ONE/76502.java
Programmers/[76502] 괄호 회전하기/ONE/README.md

ONE: [76502] 괄호 회전하기

---

Programmers/[87694] 아이템 줍기/ONE/87694.java
Programmers/[87694] 아이템 줍기/ONE/README.md

ONE: [87694] 아이템 줍기

---

Programmers/[87391] 공 이동 시뮬레이션/ONE/87391.java
Programmers/[87391] 공 이동 시뮬레이션/ONE/README.md

ONE: [87391] 공 이동 시뮬레이션

---

Programmers/[76502] 괄호 회전하기/woong-jae/76502.js
Programmers/[76502] 괄호 회전하기/woong-jae/README.md

woong-jae: [76502] 괄호 회전하기

---

Programmers/[87694] 아이템 줍기/woong-jae/87694.js
Programmers/[87694] 아이템 줍기/woong-jae/README.md

woong-jae: [87694] 아이템 줍기

---

Programmers/[87391] 공 이동 시뮬레이션/woong-jae/87391.js
Programmers/[87391] 공 이동 시뮬레이션/woong-jae/README.md

woong-jae: [87391] 공 이동 시뮬레이션

---

Programmers/[86054] 안티세포/woong-jae/86054_fail.js
Programmers/[86054] 안티세포/woong-jae/README.md

woong-jae: [86054] 안티세포

---

BOJ/[16172] 나는 친구가 적다 (Large)/ONE/16172.java
BOJ/[16172] 나는 친구가 적다 (Large)/ONE/README.md

ONE: [16172] 나는 친구가 적다 (Large)

---

BOJ/[2800] 괄호 제거/ONE/2800.java
BOJ/[2800] 괄호 제거/ONE/README.md

ONE: [2800] 괄호 제거

---

BOJ/[12908] 텔레포트 3/ONE/12908.java
BOJ/[12908] 텔레포트 3/ONE/README.md

ONE: [12908] 텔레포트 3

---

BOJ/[2026] 소풍/ONE/2026.java
BOJ/[2026] 소풍/ONE/README.md

ONE: [2026] 소풍

---

BOJ/[1726] 로봇/ONE/1726.java
BOJ/[1726] 로봇/ONE/README.md

ONE: [1726] 로봇

---

BOJ/[1726] 로봇/Johoseong/1726.py
BOJ/[1726] 로봇/Johoseong/README.md

Johoseong: [1726] 로봇

---

BOJ/[2026] 소풍/Johoseong/2026.py
BOJ/[2026] 소풍/Johoseong/README.md

- 시간 복잡도: O(N^2*logN)? O(N^3)?

Johoseong: [2026] 소풍

---

BOJ/[16172] 나는 친구가 적다 (Large)/Johoseong/16172.py
BOJ/[16172] 나는 친구가 적다 (Large)/Johoseong/README.md

- 시간 복잡도: O(N+M) (N: 원문 길이, M: 키워드 길이)

Johoseong: [16172] 나는 친구가 적다 (Large)

---

BOJ/[16172] 나는 친구가 적다 (Large)/KingDonggyu/16172.js
BOJ/[16172] 나는 친구가 적다 (Large)/KingDonggyu/README.md

KingDonggyu: [16172] 나는 친구가 적다 (Large)

---

BOJ/[12908] 텔레포트 3/KingDonggyu/12908.js
BOJ/[12908] 텔레포트 3/KingDonggyu/README.md

시간 복잡도 : O(N!), (N = 6 = 텔레포트 수)

KingDonggyu: [12908] 텔레포트 3

---

BOJ/[2026] 소풍/KingDonggyu/2026.js
BOJ/[2026] 소풍/KingDonggyu/README.md

시간 복잡도 : O(N^2logN), 사실 잘 모르겠음..ㅋ

KingDonggyu: [2026] 소풍

---

BOJ/[2800] 괄호 제거/JFe/2800.py
BOJ/[2800] 괄호 제거/JFe/README.md

JFe: [2800] 괄호 제거

---

BOJ/[2026] 소풍/JFe/2026.py
BOJ/[2026] 소풍/JFe/README.md

JFe: [2026] 소풍

---

BOJ/[1726] 로봇/JFe/1726.py
BOJ/[1726] 로봇/JFe/README.md

JFe: [1726] 로봇

---

BOJ/[1726] 로봇/woong-jae/1726.js
BOJ/[1726] 로봇/woong-jae/README.md

woong-jae: [1726] 로봇

---

BOJ/[2026] 소풍/woong-jae/2026.js
BOJ/[2026] 소풍/woong-jae/README.md

woong-jae: [2026] 소풍

---

BOJ/[12908] 텔레포트 3/woong-jae/12908.js
BOJ/[12908] 텔레포트 3/woong-jae/README.md

woong-jae: [12908] 텔레포트 3

---

BOJ/[2800] 괄호 제거/woong-jae/2800.js
BOJ/[2800] 괄호 제거/woong-jae/README.md

woong-jae: [2800] 괄호 제거

---

BOJ/[16172] 나는 친구가 적다 (Large)/woong-jae/16172.js
BOJ/[16172] 나는 친구가 적다 (Large)/woong-jae/README.md

woong-jae: [16172]: 나는 친구가 적다 (Large)

---

Programmers/[12900] 2 x n 타일링/KingDonggyu/12900.js
Programmers/[12900] 2 x n 타일링/KingDonggyu/README.md

KingDonggyu: [12900] 2 x n 타일링

---

Programmers/[12900] 2 x n 타일링/ONE/12900.java
Programmers/[12900] 2 x n 타일링/ONE/README.md

ONE: [12900] 2 x n 타일링

---

Programmers/[12978] 배달/ONE/12978.java
Programmers/[12978] 배달/ONE/README.md

ONE: [12978] 배달

---

Programmers/[68646] 풍선 터트리기/ONE/68646.java
Programmers/[68646] 풍선 터트리기/ONE/README.md

ONE: [68646] 풍선 터트리기

---

Programmers/[12904] 가장 긴 팰린드롬/ONE/12904.java
Programmers/[12904] 가장 긴 팰린드롬/ONE/README.md

ONE: [12904] 가장 긴 팰린드롬

---

Programmers/[12929] 올바른 괄호의 갯수/ONE/12929.java
Programmers/[12929] 올바른 괄호의 갯수/ONE/README.md

ONE: [12929] 올바른 괄호의 갯수

---

Programmers/[12978] 배달/Johoseong/12978.py
Programmers/[12978] 배달/Johoseong/README.md

Johoseong: [12978] 배달

---

Programmers/[68646] 풍선 터트리기/Johoseong/68646.py
Programmers/[68646] 풍선 터트리기/Johoseong/README.md

Johoseong: [68646] 풍선 터트리기

---

Programmers/[12904] 가장 긴 팰린드롬/Johoseong/12904.py
Programmers/[12904] 가장 긴 팰린드롬/Johoseong/README.md

Johoseong: [12904] 가장 긴 팰린드롬

---

Programmers/[12978] 배달/JFe/12978.py
Programmers/[12978] 배달/JFe/README.md

JFe: [12978] 배달

---

Programmers/[12904] 가장 긴 팰린드롬/JFe/12904.py
Programmers/[12904] 가장 긴 팰린드롬/JFe/README.md

JFe: [12904] 가장 긴 팰린드롬

---

Programmers/[12929] 올바른 괄호의 갯수/JFe/12929.py
Programmers/[12929] 올바른 괄호의 갯수/JFe/README.md

JFe: [12929] 올바른 괄호의 갯수

---

Programmers/[12978] 배달/woong-jae/12978.js
Programmers/[12978] 배달/woong-jae/README.md

woong-jae: [12978] 배달

---

Programmers/[12929] 올바른 괄호의 갯수/woong-jae/12929.js
Programmers/[12929] 올바른 괄호의 갯수/woong-jae/README.md

woong-jae: [12929] 올바른 괄호의 갯수

---

Programmers/[68646] 풍선 터트리기/woong-jae/68646.js
Programmers/[68646] 풍선 터트리기/woong-jae/README.md

woong-jae: [68646] 풍선 터트리기

---

Programmers/[68645] 삼각 달팽이/ONE/68645.java
Programmers/[68645] 삼각 달팽이/ONE/README.md

ONE: [68645] 삼각 달팽이

---

Programmers/[70129] 이진 변환 반복하기/ONE/70129.java
Programmers/[70129] 이진 변환 반복하기/ONE/README.md

ONE: [70129] 이진 변환 반복하기

---

Programmers/[12979] 기지국 설치/ONE/12979.java
Programmers/[12979] 기지국 설치/ONE/README.md

ONE: [12979] 기지국 설치

---

Programmers/[12987] 숫자 게임/ONE/12987.java
Programmers/[12987] 숫자 게임/ONE/README.md

ONE: [12987] 숫자 게임

---

Programmers/[12984] 지형 편집/ONE/12984.java
Programmers/[12984] 지형 편집/ONE/README.md

ONE: [12984] 지형 편집

---

Programmers/[12987] 숫자 게임/woong-jae/12987.js
Programmers/[12987] 숫자 게임/woong-jae/README.md

woong-jae: [12987] 숫자 게임

---

Programmers/[12979] 기지국 설치/woong-jae/12979.js
Programmers/[12979] 기지국 설치/woong-jae/README.md

woong-jae: [12979] 기지국 설치

---

Programmers/[70129] 이진 변환 반복하기/woong-jae/70129.js
Programmers/[70129] 이진 변환 반복하기/woong-jae/README.md

woong-jae: [70129] 이진 변환 반복하기

---

Programmers/[12987] 숫자 게임/JFe/12987.py
Programmers/[12987] 숫자 게임/JFe/README.md

JFe: [12987] 숫자 게임

---

Programmers/[12984] 지형 편집/JFe/12984.py
Programmers/[12984] 지형 편집/JFe/README.md

JFe: [12984] 지형 편집

---

Programmers/[68645] 삼각 달팽이/KingDonggyu/68645.js
Programmers/[68645] 삼각 달팽이/KingDonggyu/README.md

KingDonggyu: [68645] 삼각 달팽이

---

Programmers/[12984] 지형 편집/KingDonggyu/12984.js
Programmers/[12984] 지형 편집/KingDonggyu/README.md

KingDonggyu: [12984] 지형 편집

---

Programmers/[12984] 지형 편집/Johoseong/12984.py
Programmers/[12984] 지형 편집/Johoseong/README.md

Johoseong: [12984] 지형 편집

---

Programmers/[12979] 기지국 설치/Johoseong/12979.py
Programmers/[12979] 기지국 설치/Johoseong/README.md

Johoseong: [12979] 기지국 설치

---

BOJ/[1562] 계단 수/woong-jae/1562.js
BOJ/[1562] 계단 수/woong-jae/README.md

woong-jae: [1562] 계단 수

---

BOJ/[1509] 팰린드롬 분할/woong-jae/1509.js
BOJ/[1509] 팰린드롬 분할/woong-jae/README.md

woong-jae: [1509] 팰린드롬 분할

---

BOJ/[2098] 외판원 순회/woong-jae/2098.js
BOJ/[2098] 외판원 순회/woong-jae/README.md

woong-jae: [2098] 외판원 순회

---

BOJ/[1562] 계단 수/ONE/1562.java
BOJ/[1562] 계단 수/ONE/README.md

ONE: [1562] 계단 수

---

BOJ/[1509] 팰린드롬 분할/ONE/1509.java
BOJ/[1509] 팰린드롬 분할/ONE/README.md

ONE: [1509] 팰린드롬 분할

---

BOJ/[2618] 경찰차/ONE/2618.java
BOJ/[2618] 경찰차/ONE/README.md

ONE: [2618] 경찰차

---

BOJ/[1328] 고층 빌딩/ONE/1328.java
BOJ/[1328] 고층 빌딩/ONE/README.md

ONE: [1328] 고층 빌딩

---

BOJ/[2098] 외판원 순회/SUbbb/2098.java
BOJ/[2098] 외판원 순회/SUbbb/README.md

SUbbb: [2098] 외판원 순회

---

BOJ/[2098] 외판원 순회/Johoseong/2098.py
BOJ/[2098] 외판원 순회/Johoseong/README.md

Johoseong: [2098] 외판원 순회

---

BOJ/[2618] 경찰차/JFe/2618.py
BOJ/[2618] 경찰차/JFe/README.md

JFe: [2618] 경찰차

---

BOJ/[1328] 고층 빌딩/JFe/1328.py
BOJ/[1328] 고층 빌딩/JFe/README.md

JFe: [1328] 고층 빌딩

---

BOJ/[1107] 리모컨/ONE/1107.java
BOJ/[1107] 리모컨/ONE/README.md

ONE: [1107] 리모컨

---

BOJ/[7662] 이중 우선순위 큐/ONE/7662.java
BOJ/[7662] 이중 우선순위 큐/ONE/README.md

ONE: [7662] 이중 우선순위 큐

---

BOJ/[1043] 거짓말/ONE/1043.java
BOJ/[1043] 거짓말/ONE/README.md

ONE: [1043] 거짓말

---

BOJ/[1167] 트리의 지름/ONE/1167.java
BOJ/[1167] 트리의 지름/ONE/README.md

ONE: [1167] 트리의 지름

---

BOJ/[1149] RGB 거리/ONE/1149.java
BOJ/[1149] RGB 거리/ONE/README.md

ONE: [1149] RGB거리

---

BOJ/[1107] 리모컨/woong-jae/1107.js
BOJ/[1107] 리모컨/woong-jae/README.md

woong-jae: [1107] 리모컨

---

BOJ/[7662] 이중 우선순위 큐/woong-jae/7662.js
BOJ/[7662] 이중 우선순위 큐/woong-jae/README.md

woong-jae: [7662] 이중 우선순위 큐

---

BOJ/[7662] 이중 우선순위 큐/KingDonggyu/7662.js
BOJ/[7662] 이중 우선순위 큐/KingDonggyu/README.md

KingDonggyu: [7662] 이중 우선순위 큐

---

BOJ/[1043] 거짓말/KingDonggyu/1043.js
BOJ/[1043] 거짓말/KingDonggyu/README.md

KingDonggyu: [1043] 거짓말

---

BOJ/[1149] RGB거리/JFe/1149.py
BOJ/[1149] RGB거리/JFe/README.md

JFe: [1149] RGB거리

---

BOJ/[1107] 리모컨/JFe/1107.py
BOJ/[1107] 리모컨/JFe/README.md

JFe: [1107] 리모컨

---

BOJ/[7662] 이중 우선순위 큐/JFe/7662.py
BOJ/[7662] 이중 우선순위 큐/JFe/README.md

JFe: [7662] 이중 우선순위 큐

---

BOJ/[1043] 거짓말/JFe/1043.py
BOJ/[1043] 거짓말/JFe/README.md

JFe: [1043] 거짓말

---

BOJ/[1167] 트리의 지름/JFe/1167.py
BOJ/[1167] 트리의 지름/JFe/README.md

JFe: [1167] 트리의 지름

---

BOJ/[1629] 곱셈/JFe/1629.py
BOJ/[1629] 곱셈/JFe/README.md

JFe: [1629] 곱셈

---

BOJ/[1238] 파티/JFe/1238.py
BOJ/[1238] 파티/JFe/README.md

JFe: [1238] 파티

---

BOJ/[1918] 후위 표기식/JFe/1918.py
BOJ/[1918] 후위 표기식/JFe/README.md

JFe: [1918] 후위 표기식

---

BOJ/[1629] 곱셈/ONE/1629.java
BOJ/[1629] 곱셈/ONE/README.md

ONE: [1629] 곱셈

---

BOJ/[1504] 특정한 최단 경로/ONE/1504.java
BOJ/[1504] 특정한 최단 경로/ONE/README.md

ONE: [1504] 특정한 최단 경로

---

BOJ/[1238] 파티/ONE/1238.java
BOJ/[1238] 파티/ONE/README.md

ONE: [1238] 파티

---

BOJ/[1918] 후위 표기식/ONE/1918.java
BOJ/[1918] 후위 표기식/ONE/README.md

ONE: [1918] 후위 표기식

---

BOJ/[1629] 곱셈/woong-jae/1629.js
BOJ/[1629] 곱셈/woong-jae/README.md

woong-jae: [1629] 곱셈

---

BOJ/[1504] 특정한 최단 경로/woong-jae/1504.js
BOJ/[1504] 특정한 최단 경로/woong-jae/README.md

woong-jae: [1504] 특정한 최단 경로

---

BOJ/[1238] 파티/woong-jae/1238.js
BOJ/[1238] 파티/woong-jae/README.md

woong-jae: [1238] 파티

---

BOJ/[1918] 후위 표기식/woong-jae/1918.js
BOJ/[1918] 후위 표기식/woong-jae/README.md

woong-jae: [1918] 후위 표기식

---

BOJ/[1629] 곱셈/KingDonggyu/1629.js
BOJ/[1629] 곱셈/KingDonggyu/README.md

KingDonggyu: [1629] 곱셈

---

BOJ/[1149] RGB거리/SUbbb/1149.java
BOJ/[1149] RGB거리/SUbbb/README.md

SUbbb: [1149] RGB거리

---

Programmers/[150369] 택배 배달과 수거하기/ONE/150369.java
Programmers/[150369] 택배 배달과 수거하기/ONE/README.md

ONE: [150369] 택배 배달과 수거하기

---

Programmers/[150365] 미로 탈출 명령어/ONE/150365.java
Programmers/[150365] 미로 탈출 명령어/ONE/README.md

ONE: [150365] 미로 탈출 명령어

---

Programmers/[150366] 표 병합/ONE/150366.java
Programmers/[150366] 표 병합/ONE/README.md

ONE: [150366] 표 병합

---

Programmers/[150367] 표현 가능한 이진트리/ONE/150367.java
Programmers/[150367] 표현 가능한 이진트리/ONE/README.md

시간복잡도 : $O(logN)$ (N: 포화 상태 이진수의 길이)

ONE: [150367] 표현 가능한 이진트리

---

Programmers/[138476] 귤 고르기/ONE/138476.java
Programmers/[138476] 귤 고르기/ONE/README.md

ONE: [138476] 귤 고르기

---

Programmers/[12905] 가장 큰 정사각형 찾/ONE/12905.java
Programmers/[12905] 가장 큰 정사각형 찾/ONE/README.md

ONE: [12905] 가장 큰 정사각형 찾기

---

Programmers/[12936] 줄 서는 방법/ONE/12936.java
Programmers/[12936] 줄 서는 방법/ONE/README.md

ONE: [12936] 줄 서는 방법

---

Programmers/[12927] 야근 지수/ONE/12927.java
Programmers/[12927] 야근 지수/ONE/README.md

ONE: [12927] 야근 지수

---

Programmers/[118670] 행렬과 연산/ONE/118670.java
Programmers/[118670] 행렬과 연산/ONE/README.md

시간복잡도: $O(NM+Q)$ (N: 행, M: 열, Q: Operation의 길이)

ONE: [118670] 행렬과 연산

---

Programmers/[118668] 코딩 테스트 공부/ONE/118668.java
Programmers/[118668] 코딩 테스트 공부/ONE/README.md

시간복잡도: $O(i * j * p)$...? (i: 목표 알고력, j: 목표 코딩력, p: 문제의 개수)

ONE: [118668] 코딩 테스트 공부

---

Programmers/[118669] 등산코스 정하기/ONE/118669.java
Programmers/[118669] 등산코스 정하기/ONE/README.md

ONE: [118669] 등산코스 정하기

---

Programmers/[152995] 인사고과/ONE/152995.java
Programmers/[152995] 인사고과/ONE/README.md

ONE: [152995] 인사고과

---

Programmers/[132266] 부대복귀/ONE/132266.java
Programmers/[132266] 부대복귀/ONE/README.md

ONE: [132266] 부대복귀

---

Programmers/[12938] 최고의 집합/ONE/12938.java
Programmers/[12938] 최고의 집합/ONE/README.md

ONE: [12938] 최고의 집합

---

Programmers/[1832] 보행자 천국/ONE/1832.java
Programmers/[1832] 보행자 천국/ONE/README.md

ONE: [1832] 보행자 천국

---

Programmers/[70130] 스타 수열/ONE/70130.java
Programmers/[70130] 스타 수열/ONE/README.md

ONE: [70130] 스타 수열

---

Programmers/[131703] 2차원 동전 뒤집기/ONE/131703.java
Programmers/[131703] 2차원 동전 뒤집기/ONE/README.md

ONE: [131703] 2차원 동전 뒤집기

---

Programmers/[136797] 숫자 타자 대회/ONE/136797.java
Programmers/[136797] 숫자 타자 대회/ONE/README.md

ONE: [136797] 숫자 타자 대회

---

Programmers/[148653] 마법의 엘리베이터/ONE/148653.java
Programmers/[148653] 마법의 엘리베이터/ONE/README.md

ONE: [148653] 마법의 엘리베이터

---

Programmers/[12920] 선입 선출 스케줄링/ONE/12920.java

ONE: [12920] 선입 선출 스케줄링
